arb-dir: lib/features/internationalization/translations
template-arb-file: en.arb
output-localization-file: translations.dart
output-dir: lib/features/internationalization/generated
output-class: Translations
nullable-getter: false