name: gym_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: 9.1.1
  
  # Functional Programming
  dartz: 0.10.1
  
  # Network
  dio: 5.9.0
  
  # Local Storage
  shared_preferences: 2.5.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  
  # Dependency Injection
  get_it: 8.2.0
  
  # Form Validation
  formz: 0.8.0
  
  # Equatable for Value Objects
  equatable: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  
  # Code Generation
  hive_generator: 2.0.1
  build_runner: 2.4.13

flutter:
  uses-material-design: true
